const figuras = [
    {   "series": 3, 
        "id":"000",
        "name": "Satoru Gojo",
        "precio":"$24.990",
        "tipo":"Jujustsu Kaisen - Gojo",
        "imagen":"https://i.postimg.cc/jjnz0j9z/gojo.png",
        "tamaño":"18.5 x 20 cm",
    },
    {   "series": 2, 
        "id":"001",
        "name": "Capitan America",
        "precio":"$30.990",
        "tipo":"El Capitan America MARVEL",
        "imagen":"https://i.postimg.cc/76g0hWqh/cap.png",
        "tamaño":" 23.5 x 22.8 cm",
    },
    {   "series": 2, 
        "id":"002",
        "name": "Spiderman",
        "precio":"$39.990",
        "tipo":"El Increible Hombre Araña - Spiderman",
        "imagen":"https://i.postimg.cc/VL7MJMPq/spider.png",
        "tamaño":"15.8 x 22.8 cm",
    },
    {   "series": 3, 
        "id":"003",
        "name": "Nezuko Kamado",
        "precio":"$19.990",
        "tipo":"Kimetsu no Yaiba - Nezuko",
        "imagen":"https://i.postimg.cc/520BggSK/nezuko.webp",
        "tamaño":"25.8 x 22.5 cm",
    },
    {   "series": 3, 
        "id":"004",
        "name": "Vegeta",
        "precio":"$19.990",
        "tipo":"Dragon Ball Super - Vegeta",        
        "imagen":"https://i.postimg.cc/Bb4DKBvg/vegeta.png",
        "tamaño":"17 x 20 cm",
    },
    {   "series": 3, 
        "id":"005",
        "name": "Batman",
        "precio":"$19.990",
        "tipo":"Ciudad Gotica - Batman",        
        "imagen":"https://i.postimg.cc/nVGqtgdw/batman.png",
        "tamaño":"15,5 x 17,1 cm",
    },
    {   "series": 2, 
        "id":"006",
        "name": "Deadpool",
        "precio":"$34.990",
        "tipo":"El Mundo de Fantasia - Deadpool",        
        "imagen":"https://i.postimg.cc/FsNXHJDr/dedpul.png",
        "tamaño":"30.8 x 25.8 cm",
    },
    {   "series": 2, 
        "id":"007",
        "name": "Wolverine",
        "precio":"$20.990",
        "tipo":"Wolverin: Inmortal",        
        "imagen":"https://i.postimg.cc/KzBCZZT3/wolverine.png",
        "tamaño":"16.8 x 25.8 cm",
    },
    {   "series": 3, 
        "id":"008",
        "name": "Bulma",
        "precio":"$12.990",
        "tipo":"Dragon Ball Super - Bulma",        
        "imagen": "https://i.postimg.cc/rFyxyj3y/bulma.png",
        "tamaño":"18.4 x 15.5 cm",
    },
    {
        "series": 1, 
        "id": "009",
        "name": "SuperMan",
        "precio": "$59.990",
        "tipo":"SuperMan Figura Exclusiva - SuperMan ",
        "imagen": "https://i.postimg.cc/vZGcQZNJ/super.png",
        "tamaño":"40.5 x 30.8 cm",
    },
    {
        "series": 1, 
        "id": "009",
        "name": "Flash",
        "precio": "$34.990",
        "tipo":"Flash la Serie (Netflix)",
        "imagen": "https://i.postimg.cc/zGcnchdz/flash.png",
        "tamaño":"16.8 x 12.8 cm",
    },
    {
        "series": 3, 
        "id": "009",
        "name": "Levi",
        "precio": "$39.990",
        "tipo":"Shingeki no Kyiojin - Levi",
        "imagen": "https://i.postimg.cc/Vk455cyd/levi.webp",
        "tamaño":"25.8 x 22.8 cm",
    },
    
    /*{
        "series": 1, 
        "id": "010",
        "name": "",
        "precio": "",
        "tipo": "",
        "comentario": "",
        "editorial": "",
        "imagen": "",
        "autor":"",
        "fecha":"",
        "paginas":"",
        "tamaño":"",
        "formato":"",
    },
    {
        "series": 1, 
        "id": "011",
        "name": "",
        "precio": "",
        "tipo": "",
        "comentario": "",
        "editorial": "",
        "imagen": "",
        "autor":"",
        "fecha":"",
        "paginas":"",
        "tamaño":"",
        "formato":"",
    },
    {
        "series": 1, 
        "id": "012",
        "name": "",
        "precio": "",
        "tipo": "",
        "comentario": "",
        "editorial": "",
        "imagen": "",
        "autor":"",
        "fecha":"",
        "paginas":"",
        "tamaño":"",
        "formato":"",
    }
    */
];

module.exports = {
    figuras
}
